---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Сайт должен работать как SPA приложение, не перезагружая страницу при переходе между разными разделами.
  - На странице товара и в каталоге должны выводиться название, рейтинг, цена со скидкой и без.
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге.
  - На странице корзины пользователь может удалить товар из корзины.
  - Корзина должна храниться в сессии браузера.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - В интернет-магазин должны быть интегрированы различные платёжные системы.
  - В интернет-магазине должны быть понятные условия оплаты, доставки и возврата товара и указание на Закон о защите прав потребителей.
  - Покупатель должен получать письмо-подтверждение на email об успешном оформлении и оплате заказа.
  - На сайте должна быть форма обратной связи или форма для заказа обратного звонка для решения возникающих вопросов.
  - Поиск по сайту должен быть реализован с автодополнением (показ товаров, совпадающих с вводимым запросом).
  - На сайте должна быть возможность перейти с любой страницы на главную по клику на лого магазина.
